//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.AssignEmployees = new HashSet<AssignEmployee>();
        }
    
        public int ProjectId { get; set; }
        public int BusinessUnitId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDetail { get; set; }
        public System.DateTimeOffset DeadlineDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignEmployee> AssignEmployees { get; set; }
        public virtual BusinessUnit BusinessUnit { get; set; }
    }
}
